#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v2
# autospec commit: f032afc
#
Name     : R-leaflet.providers
Version  : 2.0.0
Release  : 29
URL      : https://cran.r-project.org/src/contrib/leaflet.providers_2.0.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/leaflet.providers_2.0.0.tar.gz
Summary  : Leaflet Providers
Group    : Development/Tools
License  : BSD-2-Clause
Requires: R-leaflet.providers-license = %{version}-%{release}
Requires: R-htmltools
BuildRequires : R-htmltools
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# leaflet.providers
<!-- badges: start -->
[![CRAN
status](https://www.r-pkg.org/badges/version/leaflet.providers)](https://CRAN.R-project.org/package=leaflet.providers)
[![R-CMD-check](https://github.com/rstudio/leaflet.providers/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/rstudio/leaflet.providers/actions)
[![Codecov test
coverage](https://codecov.io/gh/rstudio/leaflet.providers/branch/main/graph/badge.svg)](https://app.codecov.io/gh/rstudio/leaflet.providers?branch=main)

%package license
Summary: license components for the R-leaflet.providers package.
Group: Default

%description license
license components for the R-leaflet.providers package.


%prep
%setup -q -n leaflet.providers
pushd ..
cp -a leaflet.providers buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1697642924

%install
export SOURCE_DATE_EPOCH=1697642924
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-leaflet.providers
cp %{_builddir}/leaflet.providers/LICENSE.note %{buildroot}/usr/share/package-licenses/R-leaflet.providers/14a42b1f0cc970b422fa29c3c63997653f77fa89 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/leaflet.providers/DESCRIPTION
/usr/lib64/R/library/leaflet.providers/INDEX
/usr/lib64/R/library/leaflet.providers/LICENSE
/usr/lib64/R/library/leaflet.providers/Meta/Rd.rds
/usr/lib64/R/library/leaflet.providers/Meta/features.rds
/usr/lib64/R/library/leaflet.providers/Meta/hsearch.rds
/usr/lib64/R/library/leaflet.providers/Meta/links.rds
/usr/lib64/R/library/leaflet.providers/Meta/nsInfo.rds
/usr/lib64/R/library/leaflet.providers/Meta/package.rds
/usr/lib64/R/library/leaflet.providers/NAMESPACE
/usr/lib64/R/library/leaflet.providers/NEWS.md
/usr/lib64/R/library/leaflet.providers/R/leaflet.providers
/usr/lib64/R/library/leaflet.providers/R/leaflet.providers.rdb
/usr/lib64/R/library/leaflet.providers/R/leaflet.providers.rdx
/usr/lib64/R/library/leaflet.providers/help/AnIndex
/usr/lib64/R/library/leaflet.providers/help/aliases.rds
/usr/lib64/R/library/leaflet.providers/help/leaflet.providers.rdb
/usr/lib64/R/library/leaflet.providers/help/leaflet.providers.rdx
/usr/lib64/R/library/leaflet.providers/help/paths.rds
/usr/lib64/R/library/leaflet.providers/html/00Index.html
/usr/lib64/R/library/leaflet.providers/html/R.css
/usr/lib64/R/library/leaflet.providers/leaflet-providers_2.0.0.js
/usr/lib64/R/library/leaflet.providers/tests/testthat.R
/usr/lib64/R/library/leaflet.providers/tests/testthat/test-providers_data.R

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-leaflet.providers/14a42b1f0cc970b422fa29c3c63997653f77fa89
